apiVersion: v1
kind: Secret
metadata:
  name: rag-secretsb
  namespace: rag
type: Opaque
# stringData:
#   HF_TOKEN: 
#   LANGSMITH_API_KEY: 
#   OLLAMA_MODEL: 
#   RAG_TOP_K: 
#   RAG_MIN_RERANK_SCORE: 
#   EMBEDDING_MODEL: 
#   RERANKER_MODEL: 
#   VECTOR_DB_DIR: 
#   CHROMA_HOST:
#   CHROMA_API_KEY: 
#   CHROMA_TENANT: 
#   CHROMA_DATABASE: 
#   COHERE_API_KEY: 
#   COHERE_RERANK_MODEL: 
#   FASTEMBED_MODEL:
#   VOYAGE_API_KEY:
#   VOYAGE_EMBED_MODEL: 
#   LLM_PROVIDER: 
#   GROQ_API_KEY: 
#   GROQ_MODEL: 